version: '2'

services:
  zookeeper:
    image: zookeeper:latest #docker.arvancloud.ir/wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      custom_net:
        ipv4_address: 10.5.0.5
  kafka:
    image: kafka:latest ##docker.arvancloud.ir/wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "my-topic:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    extra_hosts:
      - "kafka: kafka"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms3M -Xmx3M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
 

#  kafka-ui:
#    container_name: kafka-ui
#    image: provectuslabs/kafka-ui:latest   ###docker.arvancloud.ir/provectuslabs/kafka-ui:latest
#    ports:
#      - 8080:8080
#    environment:
#      DYNAMIC_CONFIG_ENABLED: 'true'
#    volumes:
#      - ~/kui/config.yml:/etc/kafkaui/dynamic_config.yaml

